### ISSUE TITLE
Error caused by table data API change

### ISSUE THREAD

**Issue by offbeat00** [thejosejorge/futcal-for-scriptable#34] opened 2022-02-09 11:06 UTC
![image](https://user-images.githubusercontent.com/91407474/153185920-7b7df451-426b-468c-a38a-245311edfa8f.jpeg)

An error occurred while using it frequently. Do you know how to solve it?

**Comment by TheBreznsoiza** [comment] 2022-02-09 11:24
Same here, are there problems with the FotMob API?

**Comment by thejosejorge** [comment] 2022-02-09 14:57
Hi guys,

Yes, I noticed they are still making changes to the API, I am working on a quick fix for this one.

Thanks,
José

**Comment by thejosejorge** [comment] 2022-02-09 15:59
@offbeat00, @DasBlatz, can you please retry with the latest version?

**Comment by TheBreznsoiza** [comment] 2022-02-09 16:37
I can confirm it works again with the latest version 
![IMG_0913](https://user-images.githubusercontent.com/398669/153250053-73e0bf85-93c5-47a2-836f-762d87f4efab.png)

**Comment by thejosejorge** [comment] 2022-02-09 17:22
Great, thanks for the feedback @DasBlatz! I will close the ticket.

I noticed your team name is quite long so you will probably always have issues with the names not fitting on screen. If you would like you can use the "replaceText" function to shorten the names, adding whatever you want on row 652, for example:
"Eintracht Braunschweig": "E. Braunschweig",

**Closed as completed by thejosejorge** 2022-02-09 17:22 UTC
Labels: bug

**Comment by beratgashi** [comment] 2022-02-09 20:28
@thejosejorge can i know what lines did you change because i have customized a little bit the scriptable file and i cannot overwrite it!

**Comment by michel0271** [comment] 2022-02-11 17:38
What do I have to change to make it work again? I don't want to reconfigure the widget. Please help.

**Comment by offbeat00** [comment] 2022-02-12 01:13
I can confirm it works again. I'm not retry version. but modify code by and it works again. thx bro!

**Comment by michel0271** [comment] 2022-02-12 10:15
What do I have to change in the code? Can someone help me please?

**Comment by thejosejorge** [comment] 2022-02-12 16:28
@michel0271 if you check the commit you can see all the changes: https://github.com/thejosejorge/futcal-for-scriptable/commit/494f9b10198f3648d5968bd3be4fa3fa9b41e657

Basically I replaced "tableData.tables[0]" with "tableData[0]".

**Comment by michel0271** [comment] 2022-02-12 17:33
I have now reinstalled it. Was too complicated for me. It's a pity that there are always changes in the API. Can't you simplify that?
